const mongoose = require("mongoose");
const arbitratorsSchema = new mongoose.Schema({
   title:{
    type:String,
    required:true
   },
   fullName:{
    type:String,
    required:true
   },
   DateOfBirth:{
    type:String,
    required:true
   },
   Nationality:{
    type:String,
    required:true
   },
   gender:{
    type:String,
    required:true
   },
   personalAdd:{
    type:String,
    required:true
   },
   city:{
    type:String,
    required:true
   },
   country:{
    type:String,
    required:true
   },
   phone:{
    type:Number,
    required:true
   },
   telephone:{
    type:Number
   },
   email:{
    type:String,
    required:true
   },
   alternateAdd:{
    type:String
   },
   alternateCity:{
    type:String
   },
   alternateCountry:{
    type:String
   },
   alternatePhone:{
    type:Number
   },
   alternateTelephone:{
    type:Number
   },
   alternateEmail:{
    type:String
   },
   communication:{
    type:Array,
    required:true
   },
   Degree:{
    type:String,
    required:true
   },
   DatesObtained:{
    type:String,
    required:true
   },
   institutionName:{
    type:String,
    required:true
   },
   location:{
    type:String,
    required:true
   },
   knowLanguages:{
    type:{
        English:String,
        Hindi:String,
        Marathi:String,
        Arabic:String
    },
    required:true
   },
   othersInAcadamic:{
    type:String,
    required:true
    },

    organizationNameInLegal:{
        type:String,
        required:true
    },
    DateInLegal:{
        type:String,
        required:true
    },
    positionInLegal:{
        type:String,
        required:true
    },
    responsibilityInBriefinLegal:{
        type:String,
        required:true
    },
    organizationNameInNonLegal:{
        type:String,
        required:true
    },
    DateInNonLegal:{
        type:String,
        required:true
    },
    positionInNonLegal:{
        type:String,
        required:true
    },
    responsibilityInBriefInNonLegal:{
        type:String,
        required:true
    },
    judicialExperience:{
        type:String,
        required:true
    },
    fieldOfExpertise:{
        type:Array,
        required:true
    },
    othersInExpertise:{
        type:String,
        required:true
    },
    programTitleInDispute:{
        type:String,
        required:true  
    },
    DateInDispute:{
        type:String,
        required:true
    },
    institutionNameInDispute:{
        type:String,
        required:true
    },
    otherReleventInfo:{
        type:String
    },
    arbitralName:{
        type:String,
        required:true
    },
    natureOfDispute:{
        type:String,
        required:true
    },
    sumInDispute:{
        type:String,
        required:true
    },
    awardRendered:{
        type:String,
        required:true
    },
    publications:{
        type:String
    },
    organizationNameInMembership:{
        type:String
    },
    dateOfAdmission:{
        type:String
    },
    status:{
        type:String
    },
    additionalInfo:{
        type:String
    }


},{timestamps:true});

module.exports = mongoose.model("arbitration",arbitratorsSchema);
